export const PRODUCTS = [
  {
    id: 1,
    title: "Premium Crewneck Sweatshirt",
    price: "₹29.00",
    oldPrice: "₹39.00",
    tags: ["-26%"],
    image: "/images/dummy/dummy3.png",
    hoverImage: "/images/dummy/dummy4.png",
    category: "Best Selling",
    subcategory: "Sweatshirt",
    sale: true,
    new: true,
    hot: false,
    colors: [
      { name: "Black", hex: "#000000" },
      { name: "Copper", hex: "#B87333" },
      { name: "Light Grey", hex: "#D7D7D7" },
    ],
    sizes: ["S", "M", "L", "XL"],
    dimensions: { width: 1080, height: 1350 },
  },
  {
    id: 2,
    title: "Urban Streetwear Tee",
    price: "₹22.00",
    oldPrice: "₹30.00",
    tags: ["Sale!"],
    image: "/images/dummy/dummy3.png",
    hoverImage: "/images/dummy/dummy4.png",
    category: "Best Selling",
    subcategory: "T-Shirt",
    sale: true,
    new: true,
    hot: false,
    colors: [
      { name: "Dark Grey", hex: "#1E1E1E" },
      { name: "Peach", hex: "#FFE5B4" },
      { name: "Soft Blue Grey", hex: "#B0BEC5" },
    ],
    sizes: ["M", "L", "XL"],
    dimensions: { width: 1080, height: 1400 },
  },
  {
    id: 3,
    title: "Classic Oversize Tee",
    price: "₹25.00",
    tags: ["Hot"],
    image: "/images/dummy/dummy3.png",
    hoverImage: "/images/dummy/dummy4.png",
    category: "Best Selling",
    subcategory: "Oversized Tee",
    sale: true,
    new: true,
    hot: false,
    colors: [
      { name: "Black", hex: "#000000" },
      { name: "Brown", hex: "#8D6E63" },
      { name: "Off White", hex: "#ECECEC" },
    ],
    sizes: ["S", "M", "L", "XL", "XXL"],
    dimensions: { width: 1020, height: 1500 },
  },
  {
    id: 4,
    title: "Minimalist Cotton Tee",
    price: "₹27.00",
    tags: ["Trending"],
    image: "/images/dummy/dummy3.png",
    hoverImage: "/images/dummy/dummy4.png",
    category: "Best Selling",
    subcategory: "T-Shirt",
    sale: true,
    new: true,
    hot: false,
    colors: [
      { name: "Charcoal", hex: "#2F2F2F" },
      { name: "Cream", hex: "#F0D9C0" },
      { name: "Silver", hex: "#C7C7C7" },
    ],
    sizes: ["M", "L", "XL"],
    dimensions: { width: 1100, height: 1450 },
  },

  // 🆕 NEW ARRIVAL
  {
    id: 5,
    title: "Midweight Cotton Tee",
    price: "₹26.00 – ₹29.00",
    tags: ["New"],
    image: "/images/dummy/dummy3.png",
    hoverImage: "/images/dummy/dummy4.png",
    category: "New Arrival",
    subcategory: "T-Shirt",
    sale: true,
    new: true,
    hot: false,
    colors: [
      { name: "Black", hex: "#000000" },
      { name: "Beige", hex: "#F7E4C4" },
      { name: "Light Grey", hex: "#DADADA" },
    ],
    sizes: ["S", "M", "L", "XL"],
    dimensions: { width: 1080, height: 1550 },
  },
  {
    id: 6,
    title: "Soft Pastel Hoodie",
    price: "₹45.00",
    tags: ["New", "Hot"],
    image: "/images/dummy/dummy3.png",
    hoverImage: "/images/dummy/dummy4.png",
    category: "New Arrival",
    subcategory: "Hoodie",
    sale: true,
    new: true,
    hot: true,
    colors: [
      { name: "Soft Pink", hex: "#FAD4D4" },
      { name: "Cream", hex: "#FFE9C4" },
      { name: "Sky Blue", hex: "#B3E5FC" },
    ],
    sizes: ["M", "L", "XL", "XXL"],
    dimensions: { width: 1200, height: 1700 },
  },
  {
    id: 7,
    title: "Everyday Relaxed Tee",
    price: "₹24.00",
    tags: ["New"],
    image: "/images/dummy/dummy3.png",
    hoverImage: "/images/dummy/dummy4.png",
    category: "New Arrival",
    subcategory: "Relaxed Fit Tee",
    sale: true,
    new: true,
    hot: false,
    colors: [
      { name: "Black", hex: "#111111" },
      { name: "Warm Grey", hex: "#B2A18F" },
      { name: "Light Grey", hex: "#DEDEDE" },
    ],
    sizes: ["S", "M", "L"],
    dimensions: { width: 1030, height: 1380 },
  },
  {
    id: 8,
    title: "Premium Polo Shirt",
    price: "₹34.00",
    tags: ["New Arrival"],
    image: "/images/dummy/dummy3.png",
    hoverImage: "/images/dummy/dummy4.png",
    category: "New Arrival",
    subcategory: "Polo",
    sale: true,
    new: true,
    hot: false,
    colors: [
      { name: "Navy Blue", hex: "#002855" },
      { name: "Grey", hex: "#A5A5A5" },
      { name: "Beige Yellow", hex: "#F7D794" },
    ],
    sizes: ["M", "L", "XL"],
    dimensions: { width: 1100, height: 1420 },
  },

  // 🎯 GREAT OFFER
  {
    id: 9,
    title: "Youth Short Sleeve Tee",
    price: "₹20.00",
    oldPrice: "₹29.00",
    tags: ["Great Offer", "Sale!"],
    image: "/images/dummy/dummy3.png",
    hoverImage: "/images/dummy/dummy4.png",
    category: "Great Offers",
    subcategory: "T-Shirt",
    sale: true,
    new: false,
    hot: false,
    colors: [
      { name: "Jet Black", hex: "#0D0D0D" },
      { name: "Sand", hex: "#E0C3A0" },
      { name: "Silver", hex: "#CCCCCC" },
    ],
    sizes: ["S", "M", "L"],
    dimensions: { width: 980, height: 1340 },
  },
  {
    id: 10,
    title: "Fine Jersey Tee",
    price: "₹31.00",
    tags: ["Offer"],
    image: "/images/dummy/dummy3.png",
    hoverImage: "/images/dummy/dummy4.png",
    category: "Great Offers",
    subcategory: "Jersey Tee",
    sale: true,
    new: false,
    hot: false,
    colors: [
      { name: "Dark Grey", hex: "#202020" },
      { name: "Cream", hex: "#EFE0C6" },
      { name: "Light Grey", hex: "#CFCFCF" },
    ],
    sizes: ["M", "L", "XL"],
    dimensions: { width: 1120, height: 1500 },
  },
  {
    id: 11,
    title: "Printed Graphic Tee",
    price: "₹19.00",
    oldPrice: "₹28.00",
    tags: ["Discount"],
    image: "/images/dummy/dummy3.png",
    hoverImage: "/images/dummy/dummy4.png",
    category: "Great Offers",
    subcategory: "Graphic Tee",
    sale: true,
    new: false,
    hot: false,
    colors: [
      { name: "Black", hex: "#101010" },
      { name: "Peach", hex: "#F3CEA1" },
      { name: "Soft Grey", hex: "#D3D3D3" },
    ],
    sizes: ["S", "M", "L", "XL"],
    dimensions: { width: 1150, height: 1600 },
  },
  {
    id: 12,
    title: "Casual Summer Tank",
    price: "₹17.00",
    tags: ["Hot Deal"],
    image: "/images/dummy/dummy3.png",
    hoverImage: "/images/dummy/dummy4.png",
    category: "Great Offers",
    subcategory: "Tank Top",
    sale: true,
    new: false,
    hot: false,
    colors: [
      { name: "Black", hex: "#000000" },
      { name: "Peach", hex: "#FFDDC1" },
      { name: "Warm Grey", hex: "#CFCBC2" },
    ],
    sizes: ["M", "L"],
    dimensions: { width: 980, height: 1200 },
  },
];
